name: kand
version: '${project.version}'
main: fantasypvp.kand.kandMain
api-version: '1.20'
commands:
  lightning_sword:
    description: Give player a lightning sword
    usage: /lightning_sword
  dragon_gear:
    description: Give player dragon gear
    usage: /dragon_gear
  spawn:
    description: Spawn player
    usage: /spawn
  setglobalspawn:
    description: Sets the world spawn tp point
    usage: /setSpawnTp
  dashstick:
    description: gives the user a dash stick
    usage: /dashstick
  get_currency:
    description: get currency
    usage: /get_currency
  steven_gear:
    description: Give player steven gear
    usage: /steven_gear



permissions:
  kand.admin:
    description: provides access to all kand commands
    children:
      kand.lightning_sword: true
      kand.dragon_gear: true
      kand.spawn: true
      kand.setglobalspawn: true
      kand.dashstick: true
      economy.*: true
    default: op
  kand.lightning_sword:
    description: Allows player to run /lightning_sword
    default: op
  kand.dragon_gear:
    description: Allows player to run /dragon_gear
    default: op
  kand.setglobalspawn:
    description: Allows player to run /setglobalspawn
    default: op
  kand.spawn:
    description: allows player to teleport to spawn from anywhere in the world
    default: true
  giveDashItem:
    description: allows the player to run /dashstick
    default: op
  kand.economy.manage:
    description: Allows player to use economy commands
    default: op



