name: kand_smp
version: '${project.version}'
main: fantasypvp.kand_smp.Kand_smp
api-version: '1.20'
commands:
  lightning_sword:
    description: Give player a lightning sword
    usage: /lightning_sword
  spawn:
    description: Spawn player
    usage: /spawn
  setSpawnTp:
    description: Sets the world spawn tp point
    usage: /setSpawnTp
  dashstick:
    description: gives the user a dash stick
    usage: /dashstick


permissions:
  lightning_sword:
    description: Allows player to run /lightning_sword
    default: op
  setSpawnTp:
    description: allows player to run /setSpawnTp
    default: op
  giveDashItem:
    description: allows the player to run /dashstick
    default: op
